db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 766
    third.value: Third
  pool:
    size: 12
    timeout: 10
  #в виде списка объектов pools с полями size, timeout
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 4
      timeout: 4

spring.profiles.active: qa